# Generated by Django 4.0.1 on 2022-02-12 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemsfree',
            old_name='active',
            new_name='Active',
        ),
    ]
